# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Continuous Integration
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test-headless

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -am "Commit changes made by deploy" || echo "No changes to commit"

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4

      - name: Detect changes
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        run: echo "Changes made by applying formatting..."

      - name: Detect changes
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        run: echo "No changes made by applying formatting..."

